### ISSUE TITLE
Navigate to Grocery List

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#11]
**Requirement Description**
Add navigation to the Grocery List screen

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Find a pleasing and understandable icon for the Grocery Listscreen
- [x] Develop logic to navigate to Grocery List screen
- [x] Implement navigation to Grocery List screen

**Effort estimation (LOE)**
Current Level of Effort estimation is 2.5, priority would be 2,

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/6 to be completed
