### ISSUE TITLE
Navigate to Login/Register

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#12]
**Requirement Description**
Add navigation to the Login/Register screen

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Find a pleasing and understandable icon for the Login/Register screen
- [x] Develop logic to navigate to Login/Register screen
- [x] Determine if Login/Register navigation should depend on state
- [x] Implement navigation to Login/Register screen

**Effort estimation (LOE)**
Current Level of Effort estimation is 3, priority would be 2,

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/6 to be completed
