### ISSUE TITLE
Navigate to Home

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#14]
**Requirement Description**
Add navigation to the Home screen

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Find a pleasing and understandable icon for the Home screen
- [x] Develop logic to navigate to Home screen
- [x] Implement navigation to Home screen

**Effort estimation (LOE)**
Current Level of Effort estimation is 2.5, priority would be 2,

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/6 to be completed
