### ISSUE TITLE
Login/Register Page

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#18]
**Requirement Description**
Create a screen to log into or create a new account

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

- [x] Determine login and register requirements
- [x] Design a log in and register page
- [x] Determine if a login and register page looks different if a user is logged in.
- [x] Develop the login and register page
- [x] Implement the login and register page into our app.

**Effort estimation (LOE)**
Current estimated Level of Effort, on a scale of 1 to 5, would be 4. The estimated priority is Level 2, as our app would function without it, but accounts streamline  and aid with both user experience and development process.
