### ISSUE TITLE
Ability to Log In

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#19]
**Requirement Description**
Add the functionality to log into an existing account

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

- [x] Determine what information is used to log a user in
- [x] Determine how to authenticate a user's credentials.
- [x] Implement the log-in functionality across the app.

**Effort estimation (LOE)**
Current Level of Effort estimation is 3.5, priority would be Level 2.

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/18 to be completed.
