### ISSUE TITLE
Ability to log out once a user is logged in.

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#20]
**Requirement Description**
Add the functionality to log out of a currently active session.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

```[tasklist]
### Tasks
- [ ] Develop a seamless way of logging a user out.
- [ ] Implement the logging out functionality
- [ ] Determine if a user's session is successfully logged out.
```

**Effort estimation (LOE)**
Current Level of Effort estimation is 3.5, priority would be Level 2.

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/18 to be completed.
