### ISSUE TITLE
Register Account Ability

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#21]
**Requirement Description**
Add the functionality to register for a new account

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

- [x] Determine what information is used to register
- [x] Determine how to authenticate a user's credentials
- [x] Validate that a user meets our account requirements

**Effort estimation (LOE)**
Current Level of Effort estimation is 3.5, priority would be Level 2.

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/18 to be completed.
