### ISSUE TITLE
Disable Logging in After a User is Logged In

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#22]
**Requirement Description**
Disable logging in once a user has successfully logged into the app

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine if a user is successfully logged in
- [x] Determine how we plan to hide the ability to log in once a user is already logged in
- [x] Implement the inability to log into multiple accounts on a single device

**Effort estimation (LOE)**
Current Level of Effort estimation is 3.5, priority would be Level 2.

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/18  and https://github.com/dianakarpeev/mutsu/issues/19 to be completed.
