### ISSUE TITLE
Disable Logging Out when a User isn't Logged In

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#23]
Requirement Description
Disable logging out once a user has successfully logged out of the app

Work breakdown structure
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine if a user has successfully logged out
- [x] Determine how we plan to hide the ability to log out if a current user session isn't active
- [x] Implement the inability to log out if a user isn't currently logged in

Effort estimation (LOE)
Current Level of Effort estimation is 3.5, priority would be Level 2.

Additional context
Requires https://github.com/dianakarpeev/mutsu/issues/18 and https://github.com/dianakarpeev/mutsu/issues/20 to be completed.
