### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#24]
Requirement Description
Create a screen to talk about the developers of the app.

Work breakdown structure
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine a layout and functionality for the About Us page
- [x] Determine what information we wish to have on an About Us page
- [x] Implement the About Us page.

Effort estimation (LOE)
Current estimated Level of Effort, on a scale of 1 to 5, would be 1. The estimated priority is Level 3, as it is not required for functionality.
