### ISSUE TITLE
Meal Plan Page

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#25]
Requirement Description
Create a screen to develop a Meal Plan 

Work breakdown structure
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Develop the functionality behind the Meal Plan
- [x] Integrate the Meal Plan in with the rest of the app
- [x] Integrate the Meal Plan functionalities with the Grocery List

Effort estimation (LOE)
Current estimated Level of Effort, on a scale of 1 to 5, would be 3. The estimated Priority is Level 1, as it's one of the core functional features of our app.
