### ISSUE TITLE
Remove Recipes

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#30]
**Requirement Description**
Give a user the ability to remove recipes they no longer wish to have.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Develop a way to remove recipes
- [x] Determine if we want to have a user confirm the deletion of a recipe
- [x] Implement the functionality of removing recipes

**Effort estimation (LOE)**
Level of Effort is estimated to to be at 3, and Priority level is set to 2, as it's helpful and one of our business requirements, but the app would technically function without the feature.
