### ISSUE TITLE
Search through Recipes

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#33]
**Requirement Description**
Ability to plant out when each meal is eaten so a user can ensure they've planned for every meal in a week.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [ ] Determine how each meal is tracked
- [ ] Determine how to visualize that information to a user
- [ ] Determine if a warning should be made if a user doesn't have enough meals

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.25, and it's a Priority Level 2, as it's required for the app to be a success but not a functional requirement.
