### ISSUE TITLE
Add Quantity of Specific Recipes Each Week

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#34]
**Requirement Description**
Ability to increase how many times a user will be eaten in a week

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine how to account for a user eating a recipe multiple times in a week
- [x] Determine how to indicate a user has increased quantity of specific recipes
- [x] Implement the functionality as a user changes recipe quantity

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.25, and it's a Priority Level 2, as it's required for the app to be a success but not a functional requirement.
