### ISSUE TITLE
Meal Plan confirmation

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#35]
**Requirement Description**
Confirm with the user that their meal plan is to their standards with a confirmation button

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine when to confirm a user's Meal Plan is complete
- [x] Determine how to display the information for them to confirm
- [x] Implement functionality to continue to Grocery list if Plan is confirmed
- [x] Implement functionality to edit current Meal Plan if not up to a user's standards.

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.5, and it's a Priority Level 2, as it's required for the app to be a success but not a functional requirement.
