### ISSUE TITLE
Generate Grocery List from Confirmed Meal Plan

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#36]
**Requirement Description**
Generate the Grocery List for a user, once they've confirmed their meal plan is good.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine functionality of generating Grocery List
- [x] Determine how to best display Grocery List to a user
- [x] Implement the creation of Grocery List from the Meal Plan confirmation.

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.5, and it's a Priority Level 1, as it's a core axiom of our app.
