### ISSUE TITLE
Addition of Extra Ingredients to Grocery List

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#38]
**Requirement Description**
Allow a user to add extra ingredients to a created Grocery List

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine how to edit existing Grocery Lists
- [x] Determine how to add more quantities of existing Ingredients
- [x] Implement a confirmation option when a user is happy with their edits.

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.5, and it's a Priority Level 2, as it's required for the app to be a success but not a functional requirement.
