### ISSUE TITLE
Removal of Unwanted Ingredients

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#39]
**Requirement Description**
Allow a user to remove any ingredients of a created Grocery List

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Determine how to edit existing Grocery Lists
- [x] Determine how to remove ingredients or remove certain quantities of ingredients
- [x] Develop a confirmation if a user is satisfied with their edits.

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.75, and it's a Priority Level 2, as it's required for the app to be a success but not a functional requirement.
