### ISSUE TITLE
Check off Ingredients when Bought

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#40]
**Requirement Description**
Allow a user to check off ingredients from their List when they've bought them

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [ ] Determine how to check off an ingredient
- [ ] Determine where checked ingredients are within the Grocery List categories
- [ ] Determine functionality of unchecking ingredients if needed

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.5, and it's a Priority Level 2, as it's required for the app to be a success but not a functional requirement.
