### ISSUE TITLE
Convert Ingredients Into Simplest Measurements

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#41]
**Requirement Description**
Facilitate the easiest purchasing process possible by combining ingredients into their needed amounts, for easy bulk-buying.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [ ] Determine how to calculate quantities of ingredients in a Grocery List
- [ ] Facilitate the calculation into the easiest ways to read total ingredient count
- [ ] Allow user to determine bulk-buying ingredients for ease of use (example, buying 12 eggs because their list needs 9)

**Effort estimation (LOE)**
Current estimated Level of Effort is leaning towards 3.5, and it's a Priority Level 1, as it's a core axiom of our app.
