### ISSUE TITLE
Add proper UI

### ISSUE THREAD

**Issue by breannadefo** [dianakarpeev/mutsu#45]
**Requirement Description**
The app needs to have a nice UI that looks similar to the mockups we can up with.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Home Screen UI
- [x] About Us Screen UI
- [x] Meal Plan UI
- [x] Grocery List UI
- [x] Recipe Collection UI
- [x] Create/Modify new Recipe UI
- [x] Login/Register UI

**Effort estimation (LOE)**
Current estimated Level of Effort is around 2.5/5. It does not play a part in the functionality of the app, but we still want everything to be clear and nice to look at. This makes its Priority Level lower.
