### ISSUE TITLE
Create Storage

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#47]
**Task Description**
Develop functionality for local storage for a user to store their recipes and grocery lists for persistent data management

**Steps**
List all steps that are required to complete the task

- [x] Determine how to store information
- [x] Create storage of Recipe Lists
- [x] Create storage for Users
- [x] Create storage for Ingredients
- [x] Create storage for Grocery List
- [x] Optimize storage for user convenience

**Technical effort (LOE)**
Level of Effort is likely around 3.5 or 4

**Additional context**
Urgent/Immediate

**Comment by ClockWorkElementals** [comment]
Progress complete given storage for Ingredients, based on the datastore-functionality branch
