### ISSUE TITLE
Update mockups in README.md

### ISSUE THREAD

**Issue by dianakarpeev** [dianakarpeev/mutsu#49]
**Task Description**
Replace old screenshots of our application with the newer project mockups in our repository's README.md file.

**Steps**

- [x] Upload images to imgur 
- [x] Use imgur link to create markdown
- [x] Add markdown image links to README.md
- [x] Create and add placeholder image

**Technical effort (LOE)**
Very easy and simple task that shouldn't take more than ten minutes. 1/5
