### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by dianakarpeev** [dianakarpeev/mutsu#50]
**Task Description**
Polish the project before the demo. Examples of polishing can be: presentable (not superb) UI interfaces and improving code quality (proper file and variable naming, documentation...) 

**Steps**
Feel free to add as many steps as fit! 
- [x] Varied UI improvement
- [x] Rename MainActivity to a proper name
- [x] Proper documentation
- [x] Review variable/function naming

**Technical effort (LOE)**
This is a very loosely defined task, which makes it hard to predict the level of effort required. However, this is a nice to have. Ideally, this shouldn't take more effort than a 2/5. The focus should be on other, much more important tasks.
