### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#6]
**Requirement Description**
Add a navigation bar that shows up on every screen

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Design a navigation layout and style
- [x] Create a composable element for the navigation bar
- [x] Implement the navigation bar to the app

**Effort estimation (LOE)**
The current Level of Effort estimation is around average. On a scale of 1 to 5, it would be ranked around 2.5. In terms of priority, this feels like a Level 2 priority, as it is vital for our app accessibility but technically our app would function without it.
