### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by dianakarpeev** [dianakarpeev/mutsu#63]
**Task Description**
Using the accessibility scanner, scan each screen of our mobile application and resolve any detected issues.

**Steps**
List all steps that are required to complete the task
- [x] Scan Home and resolve any detected issues 
- [ ] Scan About Us and resolve any detected issues
- [x] Scan Recipe Collection and resolve any detected issues
- [x] Scan Recipe Information and resolve any detected issues
- [ ] Scan Meal Plan and resolve any detected issues
- [x] Scan Login/Register and resolve any detected issues
- [x] Scan Grocery List and resolve any detected issues
- [x] Scan Ingredients and resolve any detected issues

**Technical effort (LOE)**
This doesn't seem to be difficult, but it definitely looks time-consuming. 3.5/5
