### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by breannadefo** [dianakarpeev/mutsu#7]
**Requirement Description**
The app will have a home screen that displays information about the app.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Create compose elements to build the screen
- [x] Have it show up on app launch
- [x] Add navigation bar to screen

**Effort estimation (LOE)**
LOE would be around 1.5/5. Screen should look nice but it doesn't offer any functionality.
