### ISSUE TITLE
Non-numeric / Empty Quantity crashes

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#70]
**Requirement Description**
Setting a quantity of new ingredients to anything but a number causes the app to crash.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [ ] Attempting to add an ingredient with no quantity should not crash the app
- [ ] Attempting to add an ingredient with a non-numeric quantity should not crash the app
- [ ] A user should not be able to add a quantity that isn't a number

**Effort estimation (LOE)**
My estimate is a 1.75, should hopefully be a quick fix.
