### ISSUE TITLE
Make screens responsive

### ISSUE THREAD

**Issue by breannadefo** [dianakarpeev/mutsu#77]
**Task Description**
Edit the UI of all the pages so that they are responsive to the phone being tilted.

**Steps**
List all steps that are required to complete the task

- [ ] Make Home screen responsive
- [ ] Make About Us screen responsive
- [ ] Make Recipe Collection screen responsive
- [ ] Make Recipe Information screen responsive
- [ ] Make Meal Plan screen responsive
- [ ] Make Login/Register screen responsive
- [ ] Make Grocery List screen responsive

**Technical effort (LOE)**
LOE should be around 2/5. As for priority, this is something that will make the app much better to use, so it would probably be around Priority 2.
