### ISSUE TITLE
Navigate to Recipe Collection

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#8]
**Requirement Description**
Add navigation to the Recipe Collection screen

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Find a pleasing and understandable icon for the Recipe Collection screen
- [x] Develop logic to navigate to Recipe Collection screen
- [x] Implement navigation to Recipe Collection screen

**Effort estimation (LOE)**
Current Level of Effort estimation is 2.5, priority would be 2,

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/6 to be completed
