### ISSUE TITLE
Navigate to Meal Plan

### ISSUE THREAD

**Issue by ClockWorkElementals** [dianakarpeev/mutsu#9]
**Requirement Description**
Add navigation to the Meal Plan screen

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] Find a pleasing and understandable icon for the Meal Plan screen
- [x] Develop logic to navigate to Meal Plan screen
- [x] Implement navigation to Meal Plan screen

**Effort estimation (LOE)**
Current Level of Effort estimation is 2.5, priority would be 2,

**Additional context**
Requires https://github.com/dianakarpeev/mutsu/issues/6 to be completed
